kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: keycloak-{{ .Values.werf.env }}
  namespace: {{ .Release.Namespace | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: keycloak-{{ .Values.werf.env }}
subjects:
  - kind: ServiceAccount
    name: keycloak-{{ .Values.werf.env }}
    namespace: {{ .Release.Namespace | quote }}
