---
apiVersion: v1
data:
  ca.crt: {{ pluck .Values.global.env .Values.ca.crt | first | default .Values.ca.crt._default | b64enc }}
  tls.crt: {{ pluck .Values.global.env .Values.client.keycloak.crt | first | default .Values.client.keycloak.crt._default | b64enc }}
  tls.key: {{ pluck .Values.global.env .Values.client.keycloak.key | first | default .Values.client.keycloak.key._default | b64enc }}
kind: Secret
metadata:
  name: cockroachdb-keycloak
type: kubernetes.io/tls